spring:
  application:
    name: swagger
  profiles:
    active: uat
  config:
    import: "optional:configserver:http://localhost:7070/"
    
management:
  endpoints:
    web:
      exposure:
        include: "*"